package com.example.agentic.domain;

public enum NodeType {REQUIREMENTS, REPOSITORY_ANALYSIS, PLAN, IMPLEMENT, VERIFY, ANALYZE_FAILURE, REPAIR, RELEASE_REVIEW, APPROVAL, PACKAGE, START_APPLICATION, HEALTH_CHECK, COMPLETED}
